# Generated by Django 3.2.16 on 2023-01-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0002_auto_20230119_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='message',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
