# Generated by Django 3.2.16 on 2023-01-19 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_auto_20230119_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guests',
            field=models.PositiveIntegerField(default=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(16)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='message',
            field=models.CharField(max_length=300),
        ),
    ]
