# Generated by Django 3.2.16 on 2023-01-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_confirmed_bookings_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
