# Generated by Django 3.2.16 on 2023-01-25 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Confirmed_Bookings',
            new_name='Confirmed_Booking',
        ),
        migrations.AlterField(
            model_name='table',
            name='capacity',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_id',
            field=models.IntegerField(null=True, unique=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
